### ISSUE TITLE
Couple of things...

### ISSUE THREAD

**Issue by biobrad** [nmquijada/tormes#15]
Hi Narciso,

I hope you are doing well and having a good time on whatever you are currently researching!
Still Tormes is fantastic, but I have a few quick questions...

Is there any reason in particular spades runs with 8 threads under the condition:
if [ "$ASSEMBLER" == 'spades' ]; then
	if [ ${ASSEMBLYJOBS} -gt 1 ]; then
		$PARALLEL -j ${ASSEMBLYJOBS} -a $OUTWD/list.tmp python $SPADES --careful -1 $OUTWD/cleaned_reads/{}.ok_1.fastq.gz -2 $OUTWD/cleaned_reads/{}.ok_2.fastq.gz -o $OUTWD/assembly/{}_assembly -t 8

Do you think it would be ok for me to change the code to put the thread variable read from the initial argument there?

Also, Java and progressivemauve seems to be spitting out a few errors. I was just wondering if you have any fixes for those? I have done some googling but cannot find much on the mauve. The java one has a few options to try, I have tried one but it didn't fix the issue.
Here is the output, I have attached the output file - the mauve and java errors start at line 1621.
progressiveMauve: symbol lookup error: /home/users/harbj019/.conda/envs/tormes-1.0/bin/../lib/libMems-1.6.so.1: undefined symbol: _ZN6genome21standardizePathStringERSs
Exited with error code: 127
Exception in thread "AWT-EventQueue-0" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1758)
	at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1833)
	at javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1696)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:863)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
	at org.gel.mauve.gui.AlignFrame.completeAlignment(Unknown Source)
	at org.gel.mauve.gui.AlignWorker.finished(Unknown Source)
	at org.gel.mauve.gui.SwingWorker$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.

Thank you once again for such an awesome pipeline. Our lab is using it A LOT at the moment. We are all extremely grateful!

Cheers
Brad

[tormesslurmout.txt](https://github.com/nmquijada/tormes/files/4111671/tormesslurmout.txt)

**Comment by biobrad** [comment]
I found the fix for progressivemauve
Apparently libgenome had an update and it broke it.
If you are running in conda - just run the following:

conda install libgenome=1.3.1=h470a237_0

It looks like this also fixes the java issue.

Narciso, I am sure you are working on bigger things... but what are the chances of a tormes update? Your pipeline is by far the easiest to install and run that I have come across!

**Comment by nmquijada** [comment]
Hi Brad,
First of all, I apologize for not updating the pipeline... I moved to a different lab (and country) and it takes time to re-organize your life again... I was thinking in a big update of tormes, that will take time, but probably it makes more sense if I release a “less-ambitious” version with the main bugs fixed and some extra analysis. I hope I can release it in the following weeks 😊
I really appreciate your comments and I am happy that you are using it a lot in your lab!

Regarding the assembly with SPAdes. I devised tormes by giving big importance to its speed. Assembly is probably the most time limiting factor (as pangenome analysis can be skipped). After different trials with different species genomes, I found that 8 threads per genome was enough to ensure a good quality assembly (using less CPUs sometimes resulted in more contigs per genome and thus, worse assembly parameters such as the N50) in a decent amount of time. Hence, if you have a machine with 24 threads available, I found the analysis was quicker if we parallelize 3 assemblies (with 8 threads each) at a time than using 24 threads for only one assembly (that did not improve the quality of the assembly). That’s why I included that condition.
Good that you’re digging in the code of tormes! Of course, feel free to modify it regarding your personal purposes and trials. Also, don't hesitate to share any experience/suggestion. Every improvement is very welcome.

Regarding java and the progressiveMauve. Definitively, that is the part that more errors is causing. I am considering not to include Mauve in the main pipeline anymore, as it is not required for the downstream analysis (probably I’ll just include some code in the manual for those willing to do genome ordering against a reference). That’s great that you found a solution for the issue! I will definitively try it and include it in the following versions.

Again, thanks a lot mate!
Narciso

**Comment by nmquijada** [comment]
Hi Brad,
I hope you are fine and safe in this crazy situation...

I just updated TORMES to version 1.1, which updates the software included (some of them were giving errors to users) and allows to include genomes in the analysis. Hope it is still usefull for your research.
Best,
Narciso

**Comment by biobrad** [comment]
Hi Narciso,

Firstly I wanted to say that from both my wife and we are so sorry to see
what is happening in Spain with the Corona virus. It is truly a beautiful
country and it is devastating to see what is happening.
It is heartbreaking that it seems to target the very people in our
society who need our care and respect the most.
I sincerely hope that you and your family are safe and well through this
unprecedented state of affairs.

In regards to Tormes 1.1 - mate, it is like you are a mind reader!!! One of
the people in my lab asked me two days ago if I can do analysis on her
sequences that she had done a while ago, but she only has the .fasta files.
Not the fastq files. So I was actually looking up ways to convert them back
to fastq files as the analysis she wants done (Mash etc) all take fastqs.
You are a legend. thank you so much for continuing to support your pipeline!

Once again, I hope you are safe and well.

Cheers
Brad

**Comment by nmquijada** [comment]
Hi Brad,

Thank you very much for your words. Indeed, the situation has totally overloaded our health system and the medical stuff are really doing tremendous efforts to try to control it. Similarly, most of the people is respecting the restrictions and staying at home whenever is possible. I hope this situation can be controlled soon and we start receiving good news. My family is OK, thanks for asking. I am living in Austria now, so I'm afraid it will be some time until I can fly back to Spain again...

Glad to hear that TORMES fits well for you! Let me know if you have any issues or suggestions.

Hope you are fine and safe too,
Narciso

**Comment by biobrad** [comment]
Hi Narciso,

Austria is also a beautiful country. One day I hope you can add in two extra letters and visit my county Australia. 🙂
It is good to hear that you and your family are ok.

I make no promises as I find that the amount of time in a day does not match my ambitions, but I am going to try to configure tormes to work with Kraken2. 🙂
Kraken 2 is much more realistic for users with a home/office based bioinformatics build now that they are hashing the database and I have the kraken2 database installed on my computer.
Especially now that AMD is going to make Clusters a thing of the past (I have just bought a 12 core/24 thread processor).
The RAM is now the most expensive sticking point!

If I manage to make any headway into my ambitious goal, I will reach out if you think it is something you would like to add as an option when installing tormes?

Thank you so much for updating tormes. I know how easy it must be to move on to new exciting projects.
The new tormes release is fantastic. It installed extremely smoothly and not 1 single error was produced through the runs.

There is 1 tiny bug in the tormes report though. If you use numbered samples, when displaying the resistance profiles it makes the assumption that your numbers are part of a numbered axis...
I have attached 2 tormes reports and an image file so you will easily see what I mean.

Thank you once again mate. You are awesome.
cheers
Brad


________________________________

**Comment by nmquijada** [comment]
Hi Brad,

Yes, deffinitively Australia is my "wish to travel" list. I hope I can visit some time :)

I totally agree on what you said about Kraken2. It would deffinitively be a good improvement. Really thanks for the suggestion!
I am really glad that the new features are good for you!

I cannot see your attached reports. It has happened some times before, apparently due to the "email reply" option... If you don't mind, please try to attach them by using the GitHub webpage or either to my email: nmartinquijada at gmail dot com

Thanks again mate,
Narciso
