### ISSUE TITLE
All Tormes Fixes I have Found in one place.

### ISSUE THREAD

**Issue by biobrad** [nmquijada/tormes#16]
I love tormes. It is by far the best pipeline I have come across and I want other people to enjoy the brilliant work that Narciso has done as well.
I understand that Narciso is busy working on other projects so I hope he doesn't mind me putting these into once place to hopefully help others who want to try tormes but have a few issues with it.

After you have run all the tormes instructions provided by Narciso, you will have to do the following to get a few niggles sorted out

To get quast working properly, you will need to install the following extra quast components:
gridss, silva and busco.

The commands I used were:

quast-download-gridss
quast-download-silva
quast-download-busco

First Mauve fix:
navigate to your tormes folder and find the file named config_file.txt (should be in /tormes-1.0/files/)
The entry for MAUVE needs to be edited.
The entry that ends with 'mauve-2.4.0.r4736-0/Mauve.jar' will need to be changed.
Change the 0 after the 'r4736-' to a 1.
It should read mauve-2.4.0.r4736-1/Mauve.jar

Second Mauve fix:
progressivemauve has a dependency that had a recent update and it unfortunately broke progressivemauve.
This will culminate in a bunch of mauve errors and stack of Java Errors in your run.
To fix this, change your version of 'libgenome'
I use conda so i did the following:
conda install libgenome=1.3.1=h470a237_0

If you are having problems with the metadata file, I created a script that will populate the 'samples_metadata' file for you. Simply put the script in a folder that contains the R1 and R2.fastq.gz files that you want to run through tormes and run the script. The resulting samples_metadata file will be formatted correctly.
The script is attached.

Lastly, if you want to troubleshoot any other issues you are having Narciso advised to run tormes and have the error information go to a file. Add the following the end of the last command you put in as and argument with NO space:  &>>error-tormes.txt 2>>error-tormes.txt &
IE: tormes --metadata samples_metadata.txt --output GENOME --no_mlst --no_pangenome --threads 16&>>error-tormes.txt 2>>error-tormes.txt &

[tormes_meta_create.txt](https://github.com/nmquijada/tormes/files/4138017/tormes_meta_create.txt)

**Comment by nmquijada** [comment]
This post is simply GREAT!
Thanks a lot for your efforts summarizing the main issues and how to overcome them! I think this is going to be really useful for other users.
All the best,
Narciso

**Comment by shlomobl** [comment]
Hi,
I am just running my first run, looks good!
About the MAUVE errors:
1. I did the first and second fixes above, but still got an error
2. What downstream analysis use MAUVE output? What further errors are expected or which analysis will be affected?
3. I did not save the error log so I'll try to run it again just to reproduce the error and post
Best,
SB

**Comment by nmquijada** [comment]
Hi @shlomobl 
1. Indeed, there are some problems when running Mauve in certain systems. Have you tried to run Mauve in the command line without tormes?
2. Mauve output will be the draft genomes ordered against the reference you provided and will be used for downstream analysis. However, if you don't enable Mauve (do not add any reference with the ```--reference``` option), the "unordered" genomes will be used instead and the results will not change. The ordering sometimes facilitates comparisons between genomes using graphical interfaces (such as Mauve or Artemis) and that's why I included it in tormes. Summarizing, try to run tormes without the ```--reference``` option.
Best,
Narciso

**Comment by biobrad** [comment]
Hi All, another fix for one of the packages that gives you grief sometimes.

If you are getting errors with tbl2asn try installing: tbl2asn-forever
so, 
conda install -c bioconda  tbl2asn-forever

it will install libfaketime and tbl2asn-forever

enjoy

**Comment by nmquijada** [comment]
Hi Brad,

Thanks for the update! I've never tried to update tbl2asn by using that way.
Indeed, there's an issue with that software, as it got outdated yearly and thus stop working.
If you try to update it by its regular conda channel ( ``` conda install -c bioconda tbl2asn ``` ), sometimes still returns an error (as the version recognizes that is more than one year old).

Another option to get tbl2asn updated, is to regularly download it from its [NCBI ftp](ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools/converters/by_program/tbl2asn/) and replace this new one with the old tbl2asn that is installed in the tormes environment (you can find its location in your system by typing ``` which tbl2asn ``` ).

**Comment by Panchastico** [comment]
Hi
i have problems with quast-download-busco; tormes version 1.3.0 (This is a bug to be fixed in future versions, but I think it's a QUAST problem.) 

I cant download busco database. The bug is in this file run_busco.py
![WhatsApp Image 2023-01-19 at 1 10 49 AM](https://user-images.githubusercontent.com/118217101/213388985-634cafeb-9926-44a0-945a-5b1c643a5510.jpeg)

https://github.com/ablab/quast/issues/124

**Comment by nmquijada** [comment]
Hi @Panchastico 
Indeed, some URLs might have changed in the latest QUAST versions (TORMES was tested and uses QUAST v5.0.2). It is not a TORMES issue and running it without BUSCO won't affect TORMES functionality ;)
We are preparing a major release that will cover this issue.

In the meantime, you can try to download the files manually and place them in their correct path. I can help you with that. Just run:
```
conda activate tormes-1.3.0

#augustus
wget -O $(which tormes | sed "s/tormes$//")../lib/python3.6/site-packages/quast_libs/augustus3.2.3/augustus.tar.gz http://bioinf.uni-greifswald.de/augustus/binaries/old/augustus-3.2.3.tar.gz
tar xzvf $(which tormes | sed "s/tormes$//")../lib/python3.6/site-packages/quast_libs/augustus3.2.3/augustus.tar.gz

#bacteria
wget -O $(which tormes | sed "s/tormes$//")../lib/python3.6/site-packages/quast_libs/busco/bacteria.tar.gz http://busco.ezlab.org/v2/datasets/bacteria_odb9.tar.gz

#eukaryota
wget -O $(which tormes | sed "s/tormes$//")../lib/python3.6/site-packages/quast_libs/busco/eukaryota.tar.gz https://busco.ezlab.org/v2/datasets/eukaryota_odb9.tar.gz

#fungi
wget -O $(which tormes | sed "s/tormes$//")../lib/python3.6/site-packages/quast_libs/busco/fungi.tar.gz https://busco.ezlab.org/v2/datasets/fungi_odb9.tar.gz
```

Now, you might be able to use BUSCO functionality with QUAST in TORMES ;)

Let me know if it worked!
Narciso
