### ISSUE TITLE
Feedback on comparison between TORMES and Bactopia

### ISSUE THREAD

**Issue by rpetit3** [nmquijada/tormes#18]
Hi @nmquijada 

I've developed a tool similar to TORMES, called Bactopia (https://github.com/bactopia/bactopia). I'm planning to submit a preprint very soon. In this preprint I make some comparisons to TORMES, if possible I'd like to get your feedback on my comparisons before submission.

Please feel free to contact me at robert.petit@emory.edu so that I can share our draft with you. 

Thanks!
Robert

**Comment by nmquijada** [comment]
Dear Robert,
Thanks for the message. Sure! I will send you an email.
Narciso
