### ISSUE TITLE
Error(s) when running - many -"no such files or directory" and others

### ISSUE THREAD

**Issue by shawndy** [nmquijada/tormes#23]
Hello,

I am running for first time, installed via conda on Mint today. I get this error dump, which I think has something to do with the software not getting access to an expected config file:

after submitting:

.../TORMES$ tormes --metadata centmuts_metadata.txt --output TORMES_OUT1 --reference Ec_MG1655.fasta --threads 7 --genera Escherichia

"""
(maybe 30 or so of these...)
grep: /home/franklin/miniconda3/envs/tormes-1.1/bin/../files/config_file.txt: No such file or directory
grep: /home/franklin/miniconda3/envs/tormes-1.1/bin/../files/config_file.txt: No such file or directory
grep: /home/franklin/miniconda3/envs/tormes-1.1/bin/../files/config_file.txt: No such file or directory
/home/franklin/miniconda3/envs/tormes-1.1/bin/tormes: line 513: metadata.R: command not found
cut: reads.tmp: No such file or directory
Software:  found

ERROR: Binaries for MAUVE not found! Please check if:
	 * Binaries are not installed
	 * Binaries are installed but the path in /home/franklin/miniconda3/envs/tormes-1.1/bin/../files/config_file.txt is incorrect

Was there another conda command needed?  I can't see the error path to see where it's trying to look, but the tormes-1.1 folder and a bunch of stuff is in the miniconda3 directory.

**Comment by biobrad** [comment]
After doing conda activate tormes did you run the command tormes-setup ?

**Comment by nmquijada** [comment]
Hi @shawndy 

It seems that tormes doesn't find the config_file.txt, that is automatically created by ```tormes-setup``` script and that stores the loactiosn of the different software that will be used by tormes (in case you would like to manually change any of them).
As @biobrad said, ```tormes-setup``` has to be run after installing and activating the conda envrironment.

Have you done so?

**Comment by shawndy** [comment]
Oh boy.   I went back in bash log, I mis-typed "tormes-setup", it had errored, but I continued on (was more focused on formatting the config file and finding old data, so bash was shell was minimized and I missed it...)

Egg on Face. (Also, I thought it installed too quickly!)  I am running the setup now, thanks for help.

**Comment by biobrad** [comment]
Haha. There is no egg on face to be had.
I always say to my staff at work 'Mistakes are good! It normally means you
are trying new things.'

Personally I think if you are not making any mistakes you are not trying
hard enough. 😁

Humans are funny. There is nothing we find more uncomfortable than being
told what we are doing wrong. Yet inversely to that, it is usually the most
effective way to improve. I can't stand reading lecturers comments on my
essays but it is where I gain the most insight.
