### ISSUE TITLE
Warning: Ignoring 26 observations

### ISSUE THREAD

**Issue by alantsangmb** [nmquijada/tormes#32]
I have successfully ran and obtain html results using tormes-1.2.0
Most of the results displayed perfectly in the browser, however some warning messages are shown:

##   Consider 'structure(list(), *)' instead.

Can they be just ignored?
Anything I need to update?
Thanks.

**Comment by biobrad** [comment]
Narciso will tell you definitely... But I have been ignoring these for the
last six months with no issues.

**Comment by nmquijada** [comment]
Hi @alantsangmb 
Yes, those warnings can be ignored as they don't affect the results.
It seems that plotly (the R package for creating the interactive plots) has some issues with some deprecated functions: https://github.com/ropensci/plotly/issues/1783
So warnings appear without compromising plotly activity. I hope their developers can solve it soon.
Best,
Narciso

**Comment by alantsangmb** [comment]
Thank you! :)
