### ISSUE TITLE
WARNING: html report file could not be created

### ISSUE THREAD

**Issue by valery-shap** [nmquijada/tormes#35]
Hello, Narciso,

I have reads that I've filtered all 16s before and run tormes with these filtered reads. And seems that tormes couldn't create report file because 16S-rRNA folder Fasta files are empty. I'm not sure of this) Could it be so? I attached .err file.

Best regards,
Valery
[87565_filt copy_err.txt](https://github.com/nmquijada/tormes/files/6017889/87565_filt.copy_err.txt)

**Comment by nmquijada** [comment]
Hi Valery,

It looks very much that that was the problem, yes.
The generation of the report relies in the *tormes_report.Rmd* file, that is stored in the *report_files* directory and that it is able for user manipulation. 
We can make R to "ignore" this problem and keep rendering the report by just throwing a "warning".
For doing so:
1. uncompress the *report_files* directory:  ```tar xzf report_files.tgz``` and `cd report_files`
2. open the *tormes_report.Rmd* file in your favorite text editor.
3. in the line 221 you will find: *```{r, echo=FALSE}*
4. change it to: *```{r, echo=FALSE, error=TRUE}*
5. save the document and re-run the tormes-report generation: `./render_report.sh`

This script will use the information contained in the "new" *tormes_report.Rmd* file for the generation of your report.

Please try it out and let me know if it works. If you find troubles modifying the *tormes_report.Rmd* file, you can also share it with me.

All the best,
Narciso

**Comment by nmquijada** [comment]
Hi Valery,

We just released the new version of TORMES (v1.3.0).
This issue is solved in this newer version. Therefore, please consider updating to TORMES v.1.3.0.

Best,
Narciso

**Comment by valery-shap** [comment]
Hello, Narciso,

Thank you very much!
I'm still an active user of TORMES, but I've updated all databases.

Best regards,
Valery
