### ISSUE TITLE
Spades memory issue in 1.2 but not 1.1

### ISSUE THREAD

**Issue by dkarig** [nmquijada/tormes#36]
I previously assembled several genomes using Tormes 1.1, and around 128GB memory was sufficient.  I'm trying to redo everything using Tormes 1.2, but even when I use 1500GB, spades throws a memory error, and spades.log reads:
"<jemalloc>: Error in malloc(): out of memory"

Do you have any insights into this or how I might parameterize tormes to get around this?

As an example, I am running the following:
```
qsub -I -q bigmem -l select=1:ncpus=8:mem=1500gb,walltime=72:00:00
cd /scratch1/dkarig/tormes1_2out
conda activate tormes-1.2.1
tormes --metadata metadata_AF054_003 --output AF054_003_Bacillus --threads 8 > tormes_stdout_Bacillus.txt &
```

**Comment by biobrad** [comment]
I was having the same problem but I thought it was my memory on my computer
for highly fragmented genomes. I will have a look for you. I think the
creator of tormes might be offline at the moment. It is probably going to
be one of two things though. Either the spades version or the parameters it
uses.

**Comment by biobrad** [comment]
Hi Dkarig, 
Looks like there may have been an issues with spades 3.14.1 if you read here: 
https://github.com/ablab/spades/issues/588

You can upgrade your spades by activating the tormes environment in conda and then specifying the version you want to upgrade to.

ie:
conda activate tormes-1.2.1
conda install spades=1.15.0

I know that over the last year there have been ssl issues with conda-forge which has caused a lot of problems. I haven't tested the tormes pipeline yet with the upgrade to 1.15.0 on spades, hopefully it doesn't break anything. 
I will do a run now and report back if it works.

Cheers
Brad

**Comment by biobrad** [comment]
Hi Dkarig,
I ran the pipeline using spades 3.15.0 and it looks like it works perfectly.
cheers
Brad

**Comment by nmquijada** [comment]
Hi @dkarig 
I haven't run into this issue yet but I will try to reproduce.
Thanks @biobrad for taking care of it! Following the link you provided it very much looks like the solution.

So please upgrade to SPAdes v3.15.0 after activating *tormes-1.2.1* environment.

The SPAdes v3.13.1 is the default version that you will get when installing tormes environment. I will upgrade to the newer version of SPAdes for the next release.

Please let us know if it worked!
Narciso

**Comment by dkarig** [comment]
Thank you, @biobrad and @nmquijada.  Upgrading to Spades 3.15.0 did the trick:
`conda install -c bioconda spades=3.15.0`

-DK

**Comment by biobrad** [comment]
Nice one bruvva!
