### ISSUE TITLE
RDPTools not found

### ISSUE THREAD

**Issue by SilvanoS** [nmquijada/tormes#37]
Hello, and congrats for the Tormes tool!
I encountered an issue installing it on WSL2. During the installation process everything seems fine, but when I run it, it shows the error you can see in the attached image file. 
In the specified path there's no presence of the RDPTools folder, and of course the supposed classifier.jar inside of it. 
I also tried to install RDPTools separetely but I get the same result. 

Could you help me to solve this problem? Thank you so much in advance!

Silvano. 
![RDPTools](https://user-images.githubusercontent.com/10218512/111073100-bbe64000-84dd-11eb-8f98-2ad02691729a.png)

**Comment by biobrad** [comment]
Hi Silvano, 
Could you please provide the output of:
ls /home/silunibox/miniconda3/envs/tormes-1.2.1
and
cat /home/silunibox/miniconda3/envs/tormes-1.2.1/files/config_file.txt
and finally
conda search rdptools

cheers
Brad

**Comment by SilvanoS** [comment]
Hello Brad, thank you so much for your support!
Attached the requested outputs.
I look forward your reply!
Silvano

![envs_tormes](https://user-images.githubusercontent.com/10218512/111124263-9ce4be00-8570-11eb-87cd-1bfa64630462.png)
![tormes_config_file](https://user-images.githubusercontent.com/10218512/111124288-a4a46280-8570-11eb-9f71-16b6876f51f9.png)

**Comment by biobrad** [comment]
ah, ok I think I found the problem.
It doesn't look like you dont have bioconda set as one of your conda channels.
from your home directory, you don't need to have conda active, put in the following:

`conda config --add channels bioconda`

After this, you can try updating your conda environment with this command run from the same directory you have saved the tormes-1.2.1.yml file into:

`conda env update -n tormes-1.2.1 -f tormes-1.2.1.yml`

If that doesn't fix up the missing packages, or if it does update but you still have problems, you may have to re-install tormes again.

To delete the existing tormes install, you type in:

`conda remove -n tormes-1.2.1 --all`

then clean up the conda environment before re-installing with

`conda clean --all`

lastly, after you have tormes re-installed, it is recommended to upgrade your spades version to the latest with the following command:

`conda install -n tormes-1.2.1 spades=3.15.0`

let me know how you go!

cheers
Brad

**Comment by nmquijada** [comment]
Hi Silvano and thanks Brad for taking care that quickly of the issue!

The RDPTools are installed with the ```tormes-setup``` script by cloning the RDP github repository and compiling the files it needs from their servers. However, the RDPTools server is sometimes down and therefore the download of such files fail.

Uninstalling and installing TORMES again, as Brad suggested, would probably be the safest and quickest option, as it doesn't take much time and we will ensure that everything is properly installed and located. I checked the RDP server and it is working right now. Therefore, if you proceed with the installation of TORMES again, it might work.

Please try that and let me know.

If the installation of the RDPTools fails by other issues, we can compile it "manually" in your environment or try other means of installation.

Best,
Narciso

**Comment by biobrad** [comment]
Ah! Thanks Narciso. I was close but not quite. 🙂

**Comment by SilvanoS** [comment]
Dear Narciso, dear Brad,
thank you so much for your support!

As suggested, I uninstalled and installed TORMES again. During the process I noticed a lot of 'errors', both in the first step and during the setup process, not only regarding RDPTools. You can see them in the attached screenshots. In one of them you can see also the end of the installation where RDPTools is mentioned. 
The last screenshot is the TORMES run, and as you can see I've got the same output of the first screenshot previously posted.

Thanks again for the help!
![tormes_installation](https://user-images.githubusercontent.com/10218512/111353865-fe4a8100-8685-11eb-8dee-5c754492394f.png)

![tormes_installation_2](https://user-images.githubusercontent.com/10218512/111353916-0d313380-8686-11eb-9ccd-76c67b662874.png)
![tormes_installation_3](https://user-images.githubusercontent.com/10218512/111353924-115d5100-8686-11eb-8f57-d6190a1598ca.png)
![tormes_installation_4](https://user-images.githubusercontent.com/10218512/111353935-14584180-8686-11eb-92c4-b6b82f25564e.png)
![tormes_installation_5](https://user-images.githubusercontent.com/10218512/111353943-16ba9b80-8686-11eb-8ad3-02ff9f0a0cd1.png)

**Comment by biobrad** [comment]
Hi Silvano,

The previous command i gave for removing the tormes environment was incorrect.
Also, adding the bioconda channel may have caused some issues.
You may want to wait for Narciso to check my instructions but my suggestion (what I would do when i got these errors anyway) is the following:

Make sure you are not in any conda environments
`conda deactivate`
remove the tormes environment
`conda env remove -n tormes-1.2.1`
clean up all the conda packages and files that may have been left behind
`conda clean -a -t -i`   (type 'y' when prompted)
remove current channel priorities
`rm -f .condarc`
ensure you have the latest version of conda
`conda update -y -n base conda`
add back channel priorities
`conda config --add channels bioconda`
`conda config --add channels conda-forge`
then try installing tormes again:
`wget https://anaconda.org/nmquijada/tormes-1.2.1/2020.10.07.080943/download/tormes-1.2.1.yml`
`conda env create -n tormes-1.2.1 --file tormes-1.2.1.yml`
To activate TORMES environment run:
`conda activate tormes-1.2.1`
Additionally, the first time you are using TORMES, run (after activating TORMES environment):
`tormes-setup`

As i said, you may want to wait for Narciso to give his advice, but this is normally the process I take when I start getting clobber errors.
Also, unless you amended my command for removing the tormes environment that I gave incorrectly the last time, tormes may not have uninstalled properly which may also cause clobber errors.
(clobber is the term unix uses for when it wants to write a file to a location but a file by the same name is already in that location that is set to not be overwritten)

Sorry for the hassle, but this is all a good way to learn conda. :-)

cheers
Brad

**Comment by SilvanoS** [comment]
Hi Brad, no worries! :) Yes I used your command to remove TORMES and indeed something went wrong, because even if from the shell the command looked like it removed TORMES, looking into the miniconda3 envs directory, it was still there and I deleted it manually (probably not a great move!). 
I will try your new suggestions and wait for Narciso's advices. 

Thanks both for the help!

**Comment by biobrad** [comment]
Hi Silvano, 

I have a feeling that maybe this also wont work.
Many times I have had to re-install conda because I couldn't get it to behave again after getting clobber errors.

I have tried the method i provided you and tormes is failing due to spades errors. That could be my own install though.

Let us know if you keep running into problems.

cheers
Brad

**Comment by biobrad** [comment]
Hi Silvano

maybe try leaving conda-forge out of conda config -add channels
i have also add `-f` to the clean conda command.

I am trying this myself with a fresh install now and will let you know how I go.

cheers
Brad

**Comment by biobrad** [comment]
Hi Silvano,

Using the steps i have amended above, I have been able to confirm that my tormes install is now working correctly.

Cheers
Brad

**Comment by nmquijada** [comment]
Hi all,

Thanks Brad for your suggestions and good that it worked for you!

Silvano, the problems during the conda installation seem to be related to an incomplete removal of the environment you would like to reinstall: the packages are still present and attempts to reinstalling return errors due to duplicate/shared paths.

Any time you would like to remove tormes conda environment, do
```
conda deactivate #if you have tormes environment activated
conda env remove -n tormes-1.2.1
conda clean --all
```
This will remove the environment and its packages (won't affect the other environments you may have). There's no need to remove it manually from the ```miniconda3/envs/``` directory.

The ```.condarc``` contains the information that is displayed when running: ```conda config --show channels```
As I don't know if you removed your channels already, you can add them again (in case you didn't, this will only change the priorities)
```
conda config --add channels nmquijada
conda config --add channels conda-forge
conda config --add channels bioconda
```

Then, update conda and try to reinstall the environment again:
```
conda update conda
wget https://anaconda.org/nmquijada/tormes-1.2.1/2020.10.07.080943/download/tormes-1.2.1.yml
conda env create -n tormes-1.2.1 --file tormes-1.2.1.yml
conda activate tormes-1.2.1
tormes-setup
```

Please try to follow these steps and let me know if they worked.
First thing is to test that the TORMES environment installation was OK. If the RDPTools are still not working we will try other approaches without the need to remove the environment.

Best,
Narciso

**Comment by SilvanoS** [comment]
Hi Narciso, Hi Brad, thank you so much for taking your time with my issues, I really don't know what's happening with my workstation. I restarded from scratch, even uninstalling and reinstalling miniconda, and then following Narciso's steps. The TORMES installation seemed fine, except some errors captured by the screenshot posted below. In particular, this time even the RDPTool installation didn't give errors, but when I launched TORMES, I got the exact screenshot posted the first time. 
By the way, I installed TORMES on a laptop(!) with the same characteristics (Windows 10, WSL2, miniconda3) and following the same steps, everything went well and I was able to complete the entire TORMES pipeline!
So, what could be wrong on my working machine? 

Thank you so much in advance for all the support!
![tormes_installation_8](https://user-images.githubusercontent.com/10218512/111593033-ce0bfb00-87c9-11eb-8c19-5ce2c2428eca.png)

![tormes_installation_9](https://user-images.githubusercontent.com/10218512/111593054-d49a7280-87c9-11eb-9557-5e7bdf9a0c22.png)

**Comment by nmquijada** [comment]
Hi Silvano,

I've never tried TORMES in WSL2 but it seems like you are having a trouble when "git cloning" repositories. Thanks a lot for sharing the screenshots! It is the first time that I face such issue. I "googled" it a bit and it seems to be a common issue of WSL2 and many users posted their solutions.

Following this thread, it seems that they solved the issue by updating the wifi chipset drivers:
https://github.com/microsoft/WSL/issues/4253#issuecomment-507360165
Could you please try that?

I've seen other solutions that require a downgrade of git to version 2.21.0 (tormes installs the 2.28.0). That would be ```conda install -c conda-forge git=2.21.0```.

If you are having a problem with cloning repositories, that might also explain your issues with the RDPtools... Everything that is installed with ```tormes-setup``` uses means of installation different from conda (some of them with the ```git clone``` command).

So please, try out the first solution (update the drivers). Then uninstall and re-install the tormes environment as I told you before and let me know if it solved the problem.

If not, I will try to provide you an alternative solution avoiding the ```git clone``` command.

Best,
Narciso

**Comment by SilvanoS** [comment]
Hello Narciso, thank you so much for following my case. I'm in contact also with my University IT team. Regarding your suggestion about the updating the wifi chipset drivers, my workstation doesn't have a wifi but it uses a wired connection. I'll keep you updated until (hopefully) the solution of the problem.

Thanks a lot again for your support!

**Comment by nmquijada** [comment]
Hi Silvano,
Good! Yes please let me know how it goes. If you solve the issue that way it will help your workstation to install utilities using ```git```.
If not, we will find another solution for you to install everything.

Best,
Narciso

**Comment by SilvanoS** [comment]
Hello Narciso, finally we solved the problem! It was a software called Sophos Safeguard that was interfering with the correct installation, probably starting with the WSL2, then miniconda3 and finally TORMES. 
Now TORMES is running perfectly!
Thank you very much to You and Brad for all the help and support!

Congrats to you for the development of the TORMES pipeline!

Kind Regards

Silvano.

**Comment by nmquijada** [comment]
Hi Silvano,

Those are great news! I am happy that you solved the problem and you are ready to run TORMES!

Do not hesitate to contact in case you have any further issues :)

Have a nice evening,
Narciso
