### ISSUE TITLE
 --genera Escherichia giving error

### ISSUE THREAD

**Issue by Vikash84** [nmquijada/tormes#40]
ERROR: Software /home/miniconda3/envs/tormes-new/bin/../CGE-modules/fimtyper/fimtyper.pl required when -g/--genera \'Escherichia\' is enabled not found! Please check if:
	 * Software is not installed
	 * Software is installed but the path in /home/miniconda3/envs/tormes-new/bin/../files/config_file.txt is incorrect

**Comment by nmquijada** [comment]
Hi @Vikash84 

There's a problem with your fimtyper.pl software.
Did you run ```tormes-setup``` after installing tormes with conda?

If so, what is the output of:
```
perl /home/miniconda3/envs/tormes-new/bin/../CGE-modules/fimtyper/fimtyper.pl -h
```

Thanks,
Narciso

**Comment by Vikash84** [comment]
> Hi @Vikash84
> 
> There's a problem with your fimtyper.pl software.
> Did you run `tormes-setup` after installing tormes with conda?
> 
> If so, what is the output of:
> 
> ```
> perl /home/miniconda3/envs/tormes-new/bin/../CGE-modules/fimtyper/fimtyper.pl -h
> ```
> 
> Thanks,
> Narciso

I

**Comment by Vikash84** [comment]
Thanks Narciso,

I successfully fixed this issue.
