### ISSUE TITLE
ggtree .html report issue

### ISSUE THREAD

**Issue by geomili** [nmquijada/tormes#43]
Dear Narciso,

Congratulations on the launch of the updated tormes pipeline. It's an excellent and valuable tool.

I have installed the new tormes-1.3.0 with no flags or errors during the installation. I've then run the pipeline on a few assembled genomes and it runs fine but it fails to create the .html report reporting error:" there is no package called ggtree".

I've un-installed, cleared conda and re-installed tormes but I keep getting the same error. Any ideas on why this might be? 

I'm attaching a snip of the tormes.log file:

![image](https://user-images.githubusercontent.com/67638911/137951066-059ea34b-e0cc-42e6-8cc2-ee260fedd856.png)

**Comment by nmquijada** [comment]
Hi @geomili 

I'm glad you likedlibra tormes!
It seems that you are missing the installation of the ggtree R package (https://bioconductor.org/packages/release/bioc/html/ggtree.html). This package should be installed automatically when running ```tormes-setup```, but I have noticed that the installation by using "BiocManager" (as recommended in the installation) is sometimes giving issues. Probably this was your case. You can try to re-install by doing:

```
conda activate tormes-1.3.0
R
BiocManager::install("ggtree")
# will ask for update a/s/n of the existing packages, update them all (a)
q()
# exit R
```

If you run into issues, you can install "ggtree" locally as follows:

```
# tormes environment ust be activated
wget https://bioconductor.org/packages/release/bioc/src/contrib/ggtree_3.0.4.tar.gz
R
install.packages("aplot")
install.packages("ggtree_3.0.4.tar.gz", repos=NULL, type="source")
q()
# exit R
```

Once you have ggtree installed, you can re-run the report generation over your run. For doing so, please enter your tormes output directory and run:
```
tar xzf report_files.tgz
cd report_files
./render_report.sh
```

A new tormes_report.html will be generated in that directory (report_files/) by using the information contained in the tormes_report.Rmd file (if you have some experience with R markdown, you can definitely modify this file to customize your report!).

Let me know how it went!
Narciso

**Comment by nmquijada** [comment]
Perfect! Good to know!

I will close the issue now but feel free to reopen :)

Best,
Narciso
