### ISSUE TITLE
problem in "--isolate --gene-finding"

### ISSUE THREAD

**Issue by ariasamin** [nmquijada/tormes#45]
The tormes output is suggesting that I use these two flags (--isolate --gene-finding).  However, I can’t find any information regarding how to use them.  I’m getting error messages when I try.  Here is the command I’ m running:

ERROR: unknown option: --isolate 

ERROR: unknown option: --gene-finding

**Comment by nmquijada** [comment]
Hi @ariasamin 
Those two flags are not part of tormes, so maybe they are being shown by some of the tools included in the pipeline. 
As far as I am aware, ```--isolate``` is a flag for SPAdes and ```--gene-finding``` is a flag for QUAST.
In any case, such suggestions won't disturb your tormes run.

Could you please paste the command you used and the output that suggested you to use those flags?

Thanks!
Narciso

**Comment by ariasamin** [comment]
Thank you for your reply. 


- Command:

tormes --metadata metadata_$n --output marine_$n --threads 64 --isolate --gene-finding > tormes_stdout_$n.txt

- errors:

=== Error correction and assembling warnings:
 * 0:01:52.818    84M / 5526M WARN    General                 (launcher.cpp              : 178)   Your data seems to have high uniform coverage depth. It is strongly recommended to use --isolate option.
======= Warnings saved to /scratch1/nshamab/Tormes/marine_H2/assembly/Sample1_assembly/warnings.log
............
NOTICE: Genes are not predicted by default. Use --gene-finding or --glimmer option to enable it.

**Comment by nmquijada** [comment]
Hi @ariasamin 

Thanks for sharing the code.
Indeed, these warnings/notices were produced by SPAdes and QUAST, respectively, and didn't affect your tormes run.

Regarding QUAST, the gene finding with the ```--gene-finding``` flag is disabled by default in tormes, as gene prediction is performed in a latter step with Prodigal.
Regarding SPAdes, it has the ```--isolate``` flag that you can enable as it "is highly recommended for high-coverage isolate and multi-cell Illumina data; improves the assembly quality and running time". However, this flag cannot be used with the ```--careful``` flag of SPAdes, which aims to reduce the number of mismatches and short indels, and is enabled by default in the tormes pipeline.

If you would like to use the ```--isolate``` flag of SPAdes and see if it improves your assembly, you can definitely run the assembly from your "cleaned reads" and then include the genomes in the tormes metadata file (https://github.com/nmquijada/tormes/wiki/Shortcut-to-generate-the-metadata-file-for-TORMES) and run tormes for the downstream analysis.

For using SPAdes with the ```--isolate``` flag:
```
spades.py --isolate -1 cleaned_reads/SAMPLE.ok_1.fastq.gz -2 cleaned_reads/SAMPLE.ok_2.fastq.gz -o SAMPLE-assembly -t 64
```

Best,
Narciso

**Comment by nmquijada** [comment]
I will close this issue now.
Feel free to reopen!

Cheers,
Narciso
