### ISSUE TITLE
ggtree installation error

### ISSUE THREAD

**Issue by stevin-wilson** [nmquijada/tormes#47]
`ggtree`  installation returned an error message 
```
* installing *source* package 'ggtree' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: object 'get_aes_var' is not exported by 'namespace:rvcheck'
Execution halted
ERROR: lazy loading failed for package 'ggtree'
* removing '/home/stevin/miniconda3/envs/tormes-1.3.0/lib/R/library/ggtree'
```
while running the following command in the installation procedure:
```
tormes-setup
```

This error seems to be related to a discussion on the [Bioconductor Support forum](https://support.bioconductor.org/p/9139604)

I could get `ggtree` to install successfully by adding the line 
```
- r-rvcheck=0.1.8
```
to the 'dependencies' section of the `tormes-1.3.0.yml` file before creating conda environment using 
```
conda env create -n tormes-1.3.0 --file tormes-1.3.0.yml
```

**Comment by nmquijada** [comment]
Hi @stevin-wilson 

That is great! Thank you very much for the head's up with the issue and by posting the solution!
I will pin this issue so other users might find it while we update the improvements to the novel version.

Thanks!
Narciso
