### ISSUE TITLE
No assembly

### ISSUE THREAD

**Issue by mirand863** [nmquijada/tormes#5]
Hello,

I am trying to use your pipeline on a salmonella sample without success. It says all the dependencies are installed and after the adapter trimming step nothing seems generate results, even tough it does not give any errors. How can I solve this?

**Comment by nmquijada** [comment]
Hello,
Have you seen how many reads "survived" after quality control? (see results in the "Cleaned_reads" directory.

**Comment by quocviet0908** [comment]
Hi there, 
I also have the same problem as no clean reads could be produced after the QC step with trimmomatic and prinseq. 
I used the example trigger command with e. coli raw read data without any parameter changing.

**Comment by nmquijada** [comment]
Hello,
How long are your reads?
A user reported the same case some time ago and the error was due to the sequence length, as his reads were below 125 bp length, which is the default parameter for trimming. However, this parameter can be changed by using the --min_len option.

**Comment by quocviet0908** [comment]
Hi nmquijada,
Sorry for the late reply. I managed to run tormes by using the --min_len option as advised.

Thanks,
Viet.
