### ISSUE TITLE
ggTree installation error - part 2

### ISSUE THREAD

**Issue by biobrad** [nmquijada/tormes#50]
Hi Narciso,

Unfortunately the solution for ggtree didn't work for me, but I found another way around it. It has a few more steps but it works nicely.

1. Create a new environment in conda using the attached txt file. You will have to change it to a .yml file though. (change the txt to yml). Call the new environment tormes_report. 
`conda env create -n tormes_report --file tormes_report.yml`
3. After it has been created, activate your new environment and run the following command (NOTE: change the path to your newly created conda 'tormes_report' install path)
`Rscript -e 'library(BiocManager); BiocManager::install("ggtree", ask = FALSE, lib.loc=YOUR/CONDA/INSTALLS/PATH/miniconda3/envs/tormes_report/lib/R/library/")'`
4. Go the tormes folder where you ran the pipeline and which has your results.
5. Untar/unzip the reports file:
`tar -xzf  report_files.tgz`
6. run the following command:
`Rscript -e 'library(rmarkdown); rmarkdown::render("tormes_report.Rmd", "html_document", encoding="UTF-8")'`
7. Your Tormes report should build and you will now have a file in your folder called 'tormes-report.html.
8. PROFIT.
[tormes_report.txt](https://github.com/nmquijada/tormes/files/8360787/tormes_report.txt)

**Comment by biobrad** [comment]
Man... R is painful sometimes. Thanks for running your eye over it. Just
one thing though which you may have noticed, doesn't matter which way you
fix the issue it still mangles the core genome comparison horizontal gene
presence absence plot.

**Comment by nmquijada** [comment]
Solved with your new yml file (+ mamba if needed).
Hope this solution lasts for some time :)

**Comment by biobrad** [comment]
Fingers crossed!
