### ISSUE TITLE
tormes html report file could not be created

### ISSUE THREAD

**Issue by ryobon-dev** [nmquijada/tormes#53]
Hi, 

I installed Tormes-1.3.0 using conda and performed the program.

I encountered the error in below. It tells that there is no package called "ggtree".

Could you please let me know how to solve this issue ?

processing file: tormes_report.Rmd
  |.                                                                     |   2%
  ordinary text without R code

  |...                                                                   |   4%
label: unnamed-chunk-1 (with options)
List of 3
 $ echo   : logi FALSE
 $ message: logi FALSE
 $ warning: logi FALSE

Quitting from lines 7-17 (tormes_report.Rmd)
Error in library(ggtree) : there is no package called 'ggtree'
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> library

Execution halted

**Comment by ryobon-dev** [comment]
I am still facing on the issue.

Is there any solution ?

**Comment by biobrad** [comment]
Uninstall tormes
conda env remove -n tormes-1.3.0
# clean conda
conda clean --all
# download tormes .yml file:
wget https://anaconda.org/nmquijada/tormes-1.3.0/2021.06.08.113021/download/tormes-1.3.0.yml

Run this line to update the .yml file:
sed -i 's/dependencies\:/dependencies:\n  \- r\-rvcheck\=0\.1\.8/' tormes-1.3.0.yml

Then re-install tormes:
conda env create -n tormes-1.3.0 --file tormes-1.3.0.yml

That should sort it out.

Cheers
Brad

**Comment by ryobon-dev** [comment]
Sorry to bother you but I encountered the error in below after uninstalled tormes and re-installed.

Could you please help me again ?

tormes-1.3.0.yml.11           100%[=================================================>]     867  --.-KB/s    in 0s

2022-09-01 18:07:12 (90.6 MB/s) - ‘tormes-1.3.0.yml.11’ saved [867/867]

(base) kansensho@DESKTOP-QBEDU0F:~$ sed -i 's/dependencies\:/dependencies:\n \- r\-rvcheck\=0\.1\.8/' tormes-1.3.0.yml
(base) kansensho@DESKTOP-QBEDU0F:~$ conda env create -n tormes-1.3.0 --file tormes-1.3.0.yml

CondaValueError: invalid package specification: r-rvcheck=0.1.8 - abricate=1.0.1 - ant=1.10.0 - barrnap=0.9 - biopython=1.77 - blast=2.10.1 - cgecore=1.5.6 - fasttree=2.1.10 - git=2.28.0 - imagemagick=7.0.10_28 - kaptive=0.7.3 - kraken2=2.0.9beta - mauve=2.4.0 - mauvealigner=1.2.0 - megahit=1.2.9 - mlst=2.19.0 - parallel=20200722 - perl-data-dumper=2.173 - perl-try-tiny=0.30 - bioconda::perl-try-tiny-retry=0.004 - prinseq=0.20.4 - prokka=1.14.6 - python=3.6.11 - quast=5.0.2 - r-base=3.6.3 - r-biocmanager=1.30.10 - r-dt=0.5 - r-essentials=3.6 - r-plotly=4.9.0 - r-rmarkdown=2.1 - r-stringi=1.4.6 - rdptools=2.0.3 - roary=3.13.0 - sickle-trim=1.33 - sistr_cmd=1.1.1 - spades=3.15.2 - tabulate=0.8.7 - tormes=1.3.0 - trimmomatic=0.39

**Comment by biobrad** [comment]
Firstly, delete all tormes yml files. You have 11 of them saved.

rm -rf tormes-1.3.0.yml*

download the .yml file again and instead of using the sed command, open the
file with an editor such as nano by typing
nano tormes-1.3.0.yml

Then just under where it says dependencies: add in
- r-rvcheck=0.1.8

Be sure that it aligns with the others in terms of formatting.

Save the file by using holding down ctrl key and pressing X
Then write yes and hit enter.

Make sure you are outside of the conda base environment before attempting
install again by typing
conda deactivate

(Base) at the start of your commamd line should be gone.

Then run the install command from the tormes website again.

**Comment by ryobon-dev** [comment]
Thanks,
Tormes_report created.  From the log file, Tormes finished without any problems.

However, the following warning messages appeared. Is this related to the current Tormes version ?

Output created: tormes_report.html
Warning messages:
1: `data_frame()` was deprecated in tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.
2: `mutate_()` was deprecated in dplyr 0.7.0.
Please use `mutate()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.

**Comment by biobrad** [comment]
Ignore all those. They are just warnings wanting you to upgrade. These will
all be a thing of the past in the next release.

**Comment by ryobon-dev** [comment]
Thanks,
