### ISSUE TITLE
Eternal solving environment tormes-1.3.0.yml

### ISSUE THREAD

**Issue by imonteroo** [nmquijada/tormes#60]
Hi. I  tried to install tormes using "conda env create -n tormes-1.3.0 --file tormes-1.3.0.yml" but it stays for ever in Solving environment.

**Comment by Khabibullin543** [comment]
The same problem

**Comment by biobrad** [comment]
Hi Guys,

This may be some issue that conda is having at the moment. I was able to install ok using mamba (which is much faster and shows you what it is doing along the way).

Mamba is essentially the same as conda and uses the conda environments already installed.

Before doing any of that that, do the following:

```
conda remove -n tormes-1.3.0 --all
```
and then

```
conda clean --all
```
(select y to all the questions in conda clean)

and lastly

```
conda update -n base -c conda-forge conda
```

follow the installation instructions here for mamba:

https://mamba.readthedocs.io/en/latest/installation.html

Then, when it has installed, before running the tormes commands again...

You should already have the tormes-1.3.0.yml file downloaded from your attempt at installation.
I recommend adding a line to it to help with potential issues when creating the analysis results.
type in the following commands:

```
nano tormes-1.3.0.yml
```
add this in under 'dependencies: 
```
  - r-rvcheck=0.1.8
```
Then use ctrl-x to exit and press y to save. 
here is an example, i have added the line on the second line under dependencies(doesn't need to be the second line though)
```
$ cat tormes-1.3.0.yml 
name: tormes-1.3.0
channels:
  - nmquijada
  - conda-forge
  - bioconda
  - defaults
  - r
  - anaconda
dependencies:
  - abricate=1.0.1
  - r-rvcheck=0.1.8
  - ant=1.10.0
  - barrnap=0.9
  - biopython=1.77
  - blast=2.10.1
  - cgecore=1.5.6
etc
etc.... 
```

then install Tormes:
```
mamba env create -n tormes-1.3.0 --file tormes-1.3.0.yml
```
you can then use either conda activate tormes-1.3.0 or mamba activate tormes-1.3.0 to activate the environment.

**Comment by nmquijada** [comment]
Hi all,

Thanks a lot @biobrad for the mamba solution! I am encountering similar issues with complex environments when using conda... mamba would be definitely a good alternative to conda with these kind of issues.

@imonteroo @Khabibullin543 have you tried Brad's solution? It would be great to know if it worked for you.

If you find issues when editing the `tormes-1.3.0.yml` file by using nano, maybe you can add the package that Brad suggested automatically with sed:
```
sed -i "10i  - r-rvcheck=0.1.8" tormes-1.3.0.yml
```

Please let us know!
Narciso

**Comment by Khabibullin543** [comment]
Thank you very much, it really works!

**Comment by nmquijada** [comment]
Perfect!

We have updated the installation instructions in the main repo page :)

Best,
Narciso
