### ISSUE TITLE
New R issue ('ape' package fail) - With solution 

### ISSUE THREAD

**Issue by biobrad** [nmquijada/tormes#62]
I have encountered a new issue when running tormes-setup with the installation of 'ape'

```
** R
Error in parse(outFile) :
  /tmp/RtmpICny7q/R.INSTALLe8ec84fdd251b/ape/R/rtt.R:37:27: unexpected '>'
36:             X[,2] <- x
37:             lm.fit(X, y) |>
                              ^
ERROR: unable to collate and parse R files for package 'ape'
* removing '/home/harbj019/mambaforge/envs/tormes/lib/R/library/ape'
* installing *source* package 'rvcheck' ...
** package 'rvcheck' successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (rvcheck)
ERROR: dependency 'ape' is not available for package 'tidytree'
* removing '/home/harbj019/mambaforge/envs/tormes/lib/R/library/tidytree'
ERROR: dependencies 'ape', 'tidytree' are not available for package 'treeio'
* removing '/home/harbj019/mambaforge/envs/tormes/lib/R/library/treeio'
ERROR: dependencies 'ape', 'tidytree', 'treeio' are not available for package 'ggtree'
* removing '/home/harbj019/mambaforge/envs/tormes/lib/R/library/ggtree'
```

After a lot of trial and error, i was able to get the tormes report to generate after adding the following packages to my tormes environment

** EDIT: Doesn't need 'r-ape' installed to avoid the error in tormes-setup**
***Second Edit: adding channel in the mamba install command

```
mamba install -c bioconda bioconductor-ggtree=2.0.0
```

This is the amended .yml file if you want to start from a fresh install. 

https://github.com/biobrad/Tormes-Meta-Create/blob/main/tormes-1.3.0.yml

I have tested from a fresh install with this .yml and it stops the errors from occuring with ggtree during the tormes-setup process.

**Comment by nmquijada** [comment]
Hi Brad,

This is great! Thanks a lot for all your trials. I hope we stop hearing from ggtree issues in a while...
I will leave this issue open so other users can see, but I will move this solution (and https://github.com/nmquijada/tormes/issues/60) to the installation instructions in the main repo.

Thanks a lot!
Narciso

**Comment by Khabibullin543** [comment]
I have the same issue. I tried to install ggtree, as you wrote, but encountered the following error:

(tormes-1.3.0) khabibullinnr@microbgenome:~$ mamba install bioconductor-ggtree=2.0.0

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.3.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['bioconductor-ggtree=2.0.0']

pkgs/main/linux-64                                            No change
pkgs/r/linux-64                                               No change
pkgs/r/noarch                                                 No change
pkgs/main/noarch                                              No change

Pinned packages:
  - python 3.6.*


Could not solve for environment specs
Encountered problems while solving:
  - nothing provides requested bioconductor-ggtree 2.0.0**

The environment can't be solved, aborting the operation

**Comment by biobrad** [comment]
Try:

Mamba install -c bioconda bioconductor-ggtree=2.0.0

**Comment by nmquijada** [comment]
Solution added to the [Installation section](https://github.com/nmquijada/tormes/blob/master/README.md#installation).

Thanks a lot!
N
