### ISSUE TITLE
problems with report generation

### ISSUE THREAD

**Issue by Khabibullin543** [nmquijada/tormes#63]
Hello! Could you tell me, please, are there any workarounds to generate the html-report, without using the pipeline? None of posted solutions worked for me.

Best,
Nikita

**Comment by biobrad** [comment]
Hi Nikita,

Assuming you have already run the pipeline once and it didn't generate the report, try the following:

activate your tormes environment
```
conda activate tormes-1.3.0
```
then install bionconductor-ggtree=2.0.0 using this command:
```
conda install -c bioconda bioconductor-ggtree=2.0.0
```
then go into your tormes results from the pipeline analysis and decompress the report_files.tgz file.
```
tar -xvzf report_files.tgz
```
then go into the folder and run the render_report script

```
cd report_files/
./render_report.sh
```
let me know how you go!

**Comment by Khabibullin543** [comment]
In the end fresh install with https://github.com/biobrad/Tormes-Meta-Create/blob/main/tormes-1.3.0.yml has worked for me. Thank you very much!

**Comment by biobrad** [comment]
Great news! That saves me some testing @Narciso Martín Quijada
***@***.***> 🙂

**Comment by nmquijada** [comment]
Hi all,

Thank you very much @Khabibullin543 for the feedback and @biobrad for the new yaml!
I will update the solution in the main repo page!

Best,
Narciso
