### ISSUE TITLE
Single end fastq files?

### ISSUE THREAD

**Issue by pryratess** [nmquijada/tormes#7]
Hi! I'm interested in using your pipeline but I am using an Ion Torrent S5.  Do you have any plan to make the pipeline compatible with single-end fastq files?

**Comment by nmquijada** [comment]
Hi!
Thank you very much for your suggestion. By the moment we still plan to work with Illumina data, but that will probably change in the future, as there are some users asking for different platforms.
We will release soon the version 1.1 of TORMES that will include the possibility to start from the draft genomes and/or the raw reads. Maybe it could be an option for you, if you are able to perform the quality control of the reads and the assembly by your own and then import the draft genomes into TORMES for the downstream analysis.
I hope it helps...

**Comment by nmquijada** [comment]
Hi @pryratess 
I have already launched the version 1.1 of TORMES that allows the inclusion of already assembled genomes in the analysis.
If you were able to assemble your Ion Torrent S5 reads with any software, maybe you can import the genomes to TORMES for the downstream analysis.
Best,
Narciso
